// Dublin Bus Route Descriptions - Auto-generated from NTA VDV452 data
// Format: Route Code -> Origin - Destination
const ROUTE_DESCRIPTIONS = {
  "1": "Sandymount - Santry via O'Connell Street",
  "4": "Monkstown Avenue - Harristown",
  "6": "Howth Dart Stn - Lower Abbey Street",
  "7": "Brides Glen Luas - Mountjoy Square",
  "9": "Limekiln Avenue - Charelstown",
  "11": "Sandyford Ind Estate - Wadelai Pk",
  "13": "Grange Castle - Harristown",
  "14": "Dundrum Luas Stn - Ardlea Rd (Beaumont)",
  "15": "Ballycullen Road - Clongriffin",
  "16": "Ballinteer - Dublin Airport",
  "19": "Merrion Square - Dublin Airport",
  "26": "Fonthill Rd (Liffey Valley) - Merrion Square",
  "27": "Jobstown - Clare Hall",
  "33": "Balbriggan - Lower Abbey St",
  "37": "Blanchardstown Shopping Centre - Wilton Terrace",
  "38": "Damastown - Burlington Road",
  "39": "Ongar - Burlington Rd",
  "40": "Liffey Valley Shopping Centre - Finglas Village",
  "41": "Swords Manor - Lower Abbey Street",
  "42": "Sand's Hotel Portmarnock - Eden Quay",
  "43": "Swords Business Park - Eden Quay",
  "44": "Enniskerry - DCU",
  "47": "Belarmine - Fleet Street",
  "49": "Tallaght (The Square) - Pearse St",
  "52": "Intel - Ringsend",
  "53": "Dublin Ferryport - Talbot St",
  "60": "Rogersons Quay-Red Cow Luas",
  "65": "Blessington / Ballymore - Hawkins St",
  "68": "Newcastle / Greenogue Business Pk - Hawkins St",
  "69": "Rathcoole - Hawkins St",
  "70": "Dunboyne - Burlington Rd",
  "74": "Dundrum Luas to Eden Quay",
  "83": "Kimmage - Harristown",
  "99": "Route 99 Phoenix park Shuttle",
  "116": "Whitechurch - Parnell Square",
  "118": "Kilternan - D'Olier Street",
  "120": "Ashtown Station - Parnell St",
  "122": "Drimnagh - Ashington",
  "123": "Marino - Walinstown (Kilnamanagh Rd)",
  "130": "Castle Ave - Lwr Abbey St",
  "140": "Palmerston Park - Ballymun (Ikea)",
  "142": "Portmarnock - UCD (Belfield)",
  "150": "Rossmore - Hawkins Street",
  "151": "Foxborough (Balgaddy Rd) - Docklands (East Rd)",
  "720": "O Route Trail",
  "11B": "Phoenix Park - Donnybrook",
  "15A": "Limekiln Ave - Grand Canal Dock (Benson Street)",
  "15B": "Stocking Avenue - Grand Canal Dock (Benson Street)",
  "15D": "Whitechurch - Rinsend Road (Barrow St)",
  "16D": "Airport to Ballinteer not via Beaumont Village",
  "27A": "Blunden Drive - Eden Quay",
  "27B": "Oscar Traynor Road - Heuston Station",
  "27X": "Clare Hall - UCD Belfield",
  "32X": "UCD Belfield - Malahide",
  "33D": "Portrane to St Stephens Green",
  "33E": "Lwr Abbey St to Skerries via Portrane",
  "33X": "Skerries - Custom House Quay / St Stephen Green",
  "38A": "Damastown via Navan Rd - Burlington Rd",
  "38B": "Damastown via Ballycoolin Ind Est - Burlington Rd",
  "38D": "IBM Damastown via N3 - Burlington Rd",
  "39A": "Ongar - UCD Belfield",
  "39X": "Ongar to Burlington Road",
  "40B": "Toberburr - Parnel Street",
  "40D": "Tyrrelstown - Parnell Street",
  "40E": "Broombridge Luas to Tyrrelstown",
  "41B": "Rolestown - Lower Abbey Street",
  "41C": "Swords Manor Via River Valley - Lower Abbey St",
  "41D": "Swords Business Park - Lwr Abbey St",
  "41X": "Swords - UCD Belfield",
  "42D": "Portmarnock - DCU",
  "44B": "Glencullen - Dundrum Luas",
  "44D": "Dundrum - OCS",
  "51D": "Clondalkin - Hawkins St",
  "54A": "Ellensborough - Pearse St",
  "56A": "Tallaght - Ringsend Rd",
  "65A": "The Square Tallaght - Blessington",
  "65B": "Citywest - Hawkins St",
  "68A": "Bulfin Road - Burgh Quay",
  "69X": "Rathcoole - Hawkins St",
  "70D": "Dunboyne - DCU",
  "77A": "Citywest - Ringsend",
  "77X": "UCD Belfield - Tallaght",
  "7A": "Loughlinstown - Mountjoy Sq",
  "7B": "Shankill - Mountjoy Square",
  "7D": "Dalkey - Mountjoy Square",
  "7E": "Dalkey - Mountjoy Square via Garage",
  "83A": "Stannaway Ave - Harristown Bus Garage",
  "C1": "Adamstown Stn - Sandymount",
  "C2": "Adamstown Stn - Sandymount",
  "C3": "Maynooth - Ringsend",
  "C4": "Maynooth - Ringsend",
  "C5": "Maynooth - Ringsend Night Service",
  "C6": "Maynooth - Celbridge - Ringsend Night Service",
  "E1": "Ballywaltrim - Northwood",
  "E2": "Dun Laoghaire - Harristown",
  "G1": "Red Cow LUAS - Spencer Dock",
  "G2": "Liffey Valley SC - Spencer Dock",
  "H1": "Baldoyle - Lower Abbey Street",
  "H2": "Malahide - Lower Abbey Street",
  "H3": "Howth Summit - Lower Abbey Street",
  "L12": "Ballywaltrim - Bray Dart Station",
  "L14": "Southern Cross Road - Palermo - Cherrywood",
  "L25": "Dun Laoghaire - Dundrum Town Centre",
  "L53": "Liffey Valley - Adamstown Stn",
  "L54": "River Forest - Red Cow Luas",
  "L58": "River Forest - Castletown - Hazelhatch Stn",
  "L59": "River Forest - Celbridge - Hazelhatch",
  "N4": "Blanchardstown SC - Point Village",
  "P29": "Adamstown Stn - Ringsend",
  "S2": "Sean Moore Road - Heuston Station",
  "X1": "Kilcoole - Hawkins Street",
  "X2": "Newcastle - Hawkins Street",
  "X25": "Maynooth - Easton Rd - UCD",
  "X26": "Maynooth - Louisa Bridge - UCD",
  "X27": "Salesian College - Aghards Rd - UCD",
  "X28": "Salesian College - Celbridge Main St - UCD",
  "X30": "Dodsboro - UCD",
  "X31": "River Forest - UCD",
  "X32": "Leixlip - UCD"
};

export default ROUTE_DESCRIPTIONS;